In [71]:
import pandas as pd 
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
import nltk
print (nltk.download('stopwords'))

True

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/siddharth/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [113]:
data1=pd.read_csv("/home/siddharth/scraping/LinkedIn-Profile-Scrapper-in-Python/transcripts/final_clean_data.csv")

In [114]:
data1

,company,tital,description
0,Convosight,Convosight - Senior Data Scientist - Machine L...,Convosight is the world's first global data an...
1,Vidooly,Vidooly - Big Data Developer - AWS/Redshift/Ha...,Job DescriptionLooking for the big data engine...
2,Spinnaker Corporate Advisors,Data Science Instructor - Python/Machine Learn...,ResponsibilitiesCurrently we are looking for a...
3,Alb Associates,Manager Data Science,"Good exposure as Data scienitstWorking on R, P..."
4,Talent1st,Data Scientist - Data Mining & Modeling - R/Py...,Role & ResponsibilitiesModelling and Statistic...
...,...,...,...
75,Snaphunt Pte. Ltd,Artificial Intelligence Engineer - Data Modeli...,About The OfferDevelop and implement AI projec...
76,Eagles Hunt,Tech Lead/Architect - Java/Python/NLP (5-10 yr...,Job Description-Prior experience of high-level...
77,MERCADOS,Mercados - Data Analyst - Python/R (2-3 yrs) D...,Job title : Data AnalystReports to: L1: Manage...
78,Mindsnetwork,Data Scientist - Algorithm & Machine Learning ...,About The WorkJob Description :You will be bui...
79,Schoolybooks.com,Senior Analytics Manager - Predictive & Statis...,Job DescriptionRole :Senior Manager AnalyticsR...

In [115]:
data1.insert(3, "without_sw", "")

In [116]:
data1

,company,tital,description,without_sw
0,Convosight,Convosight - Senior Data Scientist - Machine L...,Convosight is the world's first global data an...,
1,Vidooly,Vidooly - Big Data Developer - AWS/Redshift/Ha...,Job DescriptionLooking for the big data engine...,
2,Spinnaker Corporate Advisors,Data Science Instructor - Python/Machine Learn...,ResponsibilitiesCurrently we are looking for a...,
3,Alb Associates,Manager Data Science,"Good exposure as Data scienitstWorking on R, P...",
4,Talent1st,Data Scientist - Data Mining & Modeling - R/Py...,Role & ResponsibilitiesModelling and Statistic...,
...,...,...,...,...
75,Snaphunt Pte. Ltd,Artificial Intelligence Engineer - Data Modeli...,About The OfferDevelop and implement AI projec...,
76,Eagles Hunt,Tech Lead/Architect - Java/Python/NLP (5-10 yr...,Job Description-Prior experience of high-level...,
77,MERCADOS,Mercados - Data Analyst - Python/R (2-3 yrs) D...,Job title : Data AnalystReports to: L1: Manage...,
78,Mindsnetwork,Data Scientist - Algorithm & Machine Learning ...,About The WorkJob Description :You will be bui...,
79,Schoolybooks.com,Senior Analytics Manager - Predictive & Statis...,Job DescriptionRole :Senior Manager AnalyticsR...,

In [117]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
df = pd.DataFrame()
df.insert(0, "without_sw", "") 
for i in range(0,80):
    text = data1.description[i]
    text_tokens = word_tokenize(text)
    tokens_without_sw = [word for word in text_tokens if not word in stopwords.words()]
    data1.without_sw[i]=tokens_without_sw

In [118]:
data1

,company,tital,description,without_sw
0,Convosight,Convosight - Senior Data Scientist - Machine L...,Convosight is the world's first global data an...,"[Convosight, world, 's, first, global, data, a..."
1,Vidooly,Vidooly - Big Data Developer - AWS/Redshift/Ha...,Job DescriptionLooking for the big data engine...,"[Job, DescriptionLooking, big, data, engineer,..."
2,Spinnaker Corporate Advisors,Data Science Instructor - Python/Machine Learn...,ResponsibilitiesCurrently we are looking for a...,"[ResponsibilitiesCurrently, looking, part-time..."
3,Alb Associates,Manager Data Science,"Good exposure as Data scienitstWorking on R, P...","[Good, exposure, Data, scienitstWorking, R, ,,..."
4,Talent1st,Data Scientist - Data Mining & Modeling - R/Py...,Role & ResponsibilitiesModelling and Statistic...,"[Role, &, ResponsibilitiesModelling, Statistic..."
...,...,...,...,...
75,Snaphunt Pte. Ltd,Artificial Intelligence Engineer - Data Modeli...,About The OfferDevelop and implement AI projec...,"[About, The, OfferDevelop, implement, AI, proj..."
76,Eagles Hunt,Tech Lead/Architect - Java/Python/NLP (5-10 yr...,Job Description-Prior experience of high-level...,"[Job, Description-Prior, experience, high-leve..."
77,MERCADOS,Mercados - Data Analyst - Python/R (2-3 yrs) D...,Job title : Data AnalystReports to: L1: Manage...,"[Job, title, :, Data, AnalystReports, :, L1, :..."
78,Mindsnetwork,Data Scientist - Algorithm & Machine Learning ...,About The WorkJob Description :You will be bui...,"[About, The, WorkJob, Description, :, You, bui..."
79,Schoolybooks.com,Senior Analytics Manager - Predictive & Statis...,Job DescriptionRole :Senior Manager AnalyticsR...,"[Job, DescriptionRole, :, Senior, Manager, Ana..."

In [119]:
data1.without_sw[0]

['Convosight',
 'world',
 "'s",
 'first',
 'global',
 'data',
 'analytics',
 'SaaS',
 'platform',
 'community',
 'admins',
 '.',
 'We',
 'disrupting',
 'way',
 'communities',
 'managed',
 ',',
 'moderated',
 'grown',
 'using',
 'power',
 'data',
 'analytics',
 'machine',
 'learning',
 '.',
 'Convosight',
 'funded',
 'startup',
 'engineering',
 'offices',
 'Delhi',
 'Hyderabad.Website',
 ':',
 'www.convosight.comLocation',
 ':',
 'DelhiJob',
 'description',
 'Senior',
 'Data',
 'Scientist',
 ':',
 'To',
 'lead',
 'spearhead',
 'efforts',
 'using',
 'textual',
 'analysis',
 'via',
 'Machine',
 'learning',
 'develop',
 'solutions',
 'complex',
 'business',
 'problems',
 ',',
 'looking',
 'Sr.',
 'Data',
 'Scientist',
 'lead',
 'Data',
 'Science',
 'Business',
 'Intelligence',
 '&',
 'Reporting',
 'Team.ResponsibilitiesCollaborate',
 'cross-functional',
 'teams',
 'including',
 'limited',
 'Engineering',
 ',',
 'Products',
 ',',
 'Sales',
 ',',
 'Marketing',
 '.',
 'breakdown',
 'complex',
 'business',
 'problems',
 'recommend',
 'data',
 'science',
 'ProductsUnderstand',
 'translate',
 'business',
 'solutions',
 'mathematical',
 'models',
 'work',
 'building',
 'model-based',
 'solutions',
 'around',
 'using',
 'NLP',
 'ML.Work',
 'product',
 'technology',
 'integrate',
 'model',
 'business',
 'solutions.Take',
 'full',
 'accountability',
 'data',
 '&',
 'model',
 'integrity',
 'ensure',
 'proper',
 'implementation',
 'validation',
 'modeling',
 'results.Create',
 'maintain',
 'framework',
 'around',
 'modeling',
 'data-science',
 'projects',
 'terms',
 'use',
 'models',
 ',',
 'documentation',
 'development',
 'validation',
 'scope',
 'usage.Leadership',
 'ResponsibilitiesSetup',
 'framework',
 'use',
 'cutting-edge',
 'data',
 'mining',
 ',',
 'machine',
 'learning',
 'techniquesUse',
 'techniques',
 'artificial',
 'intelligence/',
 'machine',
 'learning',
 'solve',
 'supervised',
 '&',
 'unsupervised',
 'learning',
 'problemsDesign',
 'solutions',
 'complex',
 'business',
 'problems',
 'related',
 'BIG',
 'Data',
 'using',
 'NLP/',
 'Machine',
 'Learning/',
 'Text',
 'Mining',
 'techniquesRecommend',
 '&',
 'implement',
 'best',
 'practices',
 'around',
 'application',
 'statistical',
 'modellingDevelop',
 '&',
 'implement',
 'solutions',
 'fit',
 'business',
 'problems',
 'may',
 'include',
 'applying',
 'algorithms',
 'standard',
 'statistical',
 'tool',
 'custom',
 'algorithm',
 'developmentMust',
 'HaveMasters',
 'Ph.D.',
 'degree',
 'Tier',
 '1',
 'Academic',
 'Institution',
 'Computational',
 'Mathematics',
 ',',
 'Statistics',
 ',',
 'Data',
 'Science',
 ',',
 'Machine',
 'Learning',
 'Computer',
 'Science',
 'focus',
 'Data',
 'Science.Strong',
 'foundations',
 'Data',
 'Science',
 'concepts',
 'especially',
 'text',
 'analytics',
 'NLP.7+',
 'yrs',
 '.',
 'NLP/Text',
 'AnalyticsExperience',
 'R',
 ',',
 'Python',
 'Big',
 'DataExperience',
 'building',
 'robust',
 'models',
 'using',
 'Machine',
 'Learnings.Track',
 'record',
 'driving',
 'business',
 'value',
 'growth',
 'leveraging',
 'analytics',
 'innovative',
 'SolutionsThrive',
 'fast-paced',
 'environment',
 '(',
 'ref',
 ':',
 'hirist.com',
 ')']

In [121]:
data1.to_csv('withstopwords_data.csv')